name: py build project

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  pybuildjob1:
    runs-on: ubuntu-latest
    steps:
      - name: pybuildstep1
        uses: actions/checkout@v4
      - name: pybuildsubset
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: pybuildinstaldepend
        run: pip install -r requirements.txt
      - name: executing test
        run: pytest
        continue-on-error: true
      - name: checking
        run: echo testing after error execution
      - name: docker installation env setup
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: build docker image
        run: |
          set -x

          docker version
          docker build -t pydoc .
