name: py build project

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  pybuildjob1:
    runs-on: ec2label
    steps:
      - name: login as root
        run: sudo su -
      - name: pybuildstep1
        uses: actions/checkout@v4
      - name: pybuildsubset
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: pybuildinstaldepend
        run: pip install -r requirements.txt
      - name: executing test
        run: pytest
        continue-on-error: true
      - name: checking
        run: echo testing after error execution
      - name: docker installation env setup
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: build docker image
        run: |
          set -x
          docker version
          docker build -t sensar2030/pydochub2 .
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker push
        run:  docker push sensar2030/pydochub2 
      - name: echo check ec2
        run: echo ec2selfrunnerchecks 
